# GovInfoWatcher 秘密設定ファイル
# このファイルには機密情報を記載します。Gitでの管理時はGitignoreに追加してください。

# OpenAI API設定
openai_api_key: "your-openai-api-key-here"

# Slack Webhook URL
slack_webhook_url: "https://hooks.slack.com/services/TXXXXXXXX/BXXXXXXXX/XXXXXXXXXXXXXXXXXXXXXXXX"

# メール設定
email:
  username: "your-email@example.com"
  password: "your-email-password"